import 'dart:async';
import 'dart:math';
import 'package:flutter/foundation.dart';
import '../../domain/repositories/match_repository.dart';
import '../../domain/entities/match.dart';
import '../../domain/usecases/bfs_solver.dart';
import 'package:uuid/uuid.dart';

class BotSimulationService {
  final MatchRepository _matchRepo;
  final String matchId;
  final Random _rnd = Random();
  
  bool _isRunning = false;
  MatchData? _latestMatch;
  
  // List of active bot UIDs generated by this host
  final Map<String, _BotState> _bots = {};

  BotSimulationService(this._matchRepo, this.matchId);

  void updateMatchState(MatchData data) {
    _latestMatch = data;
  }

  bool get isRunning => _isRunning;

  int get botCount => _bots.length;

  Future<void> spawnBot(String teamId, String skillLevel) async {
    if (_bots.length >= 7) return; // Prevent overcrowding

    final String botUid = 'bot_${const Uuid().v4().substring(0, 8)}';
    final String botName = 'Bot ${_rnd.nextInt(900) + 100}';
    
    // Register the bot into the RTDB
    await _matchRepo.addBot(matchId, teamId, botUid, botName);

    _bots[botUid] = _BotState(uid: botUid, teamId: teamId, skillLevel: skillLevel);
    
    // If simulation is already running, kickstart its loop
    if (_isRunning) {
      _runBotLoop(botUid);
    }
  }

  void startSimulation() {
    if (_isRunning) return;
    _isRunning = true;
    for (String botUid in _bots.keys) {
      _runBotLoop(botUid);
    }
  }

  void stopSimulation() {
    _isRunning = false;
  }

  Future<void> _runBotLoop(String botUid) async {
    while (_isRunning) {
      final botState = _bots[botUid];
      if (botState == null) break;

      // 1. Send Heartbeat to keep bot alive in Roster
      await _matchRepo.updateHeartbeat(matchId, botUid);

      // Wait a bit before making a decision (State: IDLE -> THINKING)
      await Future.delayed(Duration(milliseconds: 1000 + _rnd.nextInt(2000)));
      if (!_isRunning) break;

      final match = _latestMatch;
      if (match == null || match.meta.status != 'running') {
        await Future.delayed(const Duration(seconds: 2));
        continue;
      }

      final teamId = botState.teamId;
      final team = match.teams[teamId];
      if (team == null) continue;

      // 2. Find an available tower
      final availableTowers = team.towers.values.where((t) {
        if (t.state == 'available') return true;
        if (t.state == 'claimed' && t.claimExpiresAt != null && t.claimExpiresAt! < DateTime.now().millisecondsSinceEpoch) {
          return true; // Steal expired tower
        }
        return false;
      }).toList();

      if (availableTowers.isEmpty) {
        await Future.delayed(const Duration(seconds: 1));
        continue; // No towers right now
      }

      // Pick a random tower
      final targetTower = availableTowers[_rnd.nextInt(availableTowers.length)];

      // 3. JITTER: Prevent transaction bomb before claiming
      await Future.delayed(Duration(milliseconds: 500 + _rnd.nextInt(1000)));
      if (!_isRunning) break;

      final claimed = await _matchRepo.claimTower(matchId, teamId, targetTower.id, botUid);
      if (!claimed) continue; // Someone else grabbed it

      // 4. Calculate BFS using an Isolate (COMPUTE)
      final int targetValue = match.meta.targetValue;
      final int optimalMoves = await BfsSolver.getOptimalMoves(targetTower.startValue, targetValue);

      // 5. Apply Skill Level & Calculate Simulated Delay
      int reportedMoves = optimalMoves;
      int extraPenaltyMoves = 0;

      if (botState.skillLevel == 'random') {
        extraPenaltyMoves = _rnd.nextInt(4); // 0 to 3 extra moves
        reportedMoves += extraPenaltyMoves;
      }

      // Mathematical correlation: More moves = More time.
      // Base delay (1-2s) + (moves * 400ms)
      int simulatedSolveDelay = 1000 + _rnd.nextInt(1000) + (reportedMoves * 400);
      
      // JITTER / SIMULATED DELAY
      await Future.delayed(Duration(milliseconds: simulatedSolveDelay));
      if (!_isRunning) {
        // We stopped mid-solve, release the tower so a human can take it
        await _matchRepo.releaseTower(matchId, teamId, targetTower.id);
        break;
      }

      // 6. SOLVE TOWER
      await _matchRepo.solveTower(matchId, teamId, targetTower.id, botUid, reportedMoves, optimalMoves);
      
      // Loop repeats
    }
  }
}

class _BotState {
  final String uid;
  final String teamId;
  final String skillLevel; // 'optimal' or 'random'

  _BotState({
    required this.uid,
    required this.teamId,
    required this.skillLevel,
  });
}
